# Generated by Django 3.1.5 on 2022-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
